/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IntegracoesRouteImport } from './routes/integracoes'
import { Route as GraficosRouteImport } from './routes/graficos'
import { Route as ControleRouteImport } from './routes/controle'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracoesRoute = IntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const GraficosRoute = GraficosRouteImport.update({
  id: '/graficos',
  path: '/graficos',
  getParentRoute: () => rootRouteImport,
} as any)
const ControleRoute = ControleRouteImport.update({
  id: '/controle',
  path: '/controle',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/config': typeof ConfigRoute
  '/controle': typeof ControleRoute
  '/graficos': typeof GraficosRoute
  '/integracoes': typeof IntegracoesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/config': typeof ConfigRoute
  '/controle': typeof ControleRoute
  '/graficos': typeof GraficosRoute
  '/integracoes': typeof IntegracoesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/config': typeof ConfigRoute
  '/controle': typeof ControleRoute
  '/graficos': typeof GraficosRoute
  '/integracoes': typeof IntegracoesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/config'
    | '/controle'
    | '/graficos'
    | '/integracoes'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertas'
    | '/config'
    | '/controle'
    | '/graficos'
    | '/integracoes'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/alertas'
    | '/config'
    | '/controle'
    | '/graficos'
    | '/integracoes'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertasRoute: typeof AlertasRoute
  ConfigRoute: typeof ConfigRoute
  ControleRoute: typeof ControleRoute
  GraficosRoute: typeof GraficosRoute
  IntegracoesRoute: typeof IntegracoesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracoes': {
      id: '/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof IntegracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graficos': {
      id: '/graficos'
      path: '/graficos'
      fullPath: '/graficos'
      preLoaderRoute: typeof GraficosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controle': {
      id: '/controle'
      path: '/controle'
      fullPath: '/controle'
      preLoaderRoute: typeof ControleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertasRoute: AlertasRoute,
  ConfigRoute: ConfigRoute,
  ControleRoute: ControleRoute,
  GraficosRoute: GraficosRoute,
  IntegracoesRoute: IntegracoesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
